# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master
- dev/*

variables:
  iOSRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_iOS_v3_0_1_FULL.zip?_ga=2.39937186.1429354637.1591107319-5559409.1503304822'
  MacRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Mac_v3_0_1_FULL.zip?_ga=2.49505318.1429354637.1591107319-5559409.1503304822'
  WindowsRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_v3_0_1_FULL.zip'

jobs:
#Windows QT
- template: cicd/templates/build-Windows-qt.yml
  parameters:
    displayName: 'WindowsOpenLive'
    workingDirectory: 'OpenLive-Windows'
    scheme: 'OpenLive-Windows'
    sdkurl: $(WindowsRTCSDK)
    architecture: 'x86'
    ReleasePath: 'Release'
    QtDir: 'C:\Qt5.10.1\5.10.1\msvc2017'
